### ISSUE TITLE
Support for clusters

### ISSUE THREAD

**Issue by x64-latacora** [phronmophobic/clj-graphviz#1]
I've been using this library and it's great, but the lack of support for clusters is a significant limitation. Are there plans to implement this functionality? If not, are there any hurdles/limitations I should take into account if I try to implement it myself? I see there's a bit of code relating to clusters.

**Comment by phronmophobic** [comment]
I think I didn't add them at first because I wasn't sure what they were, but they do seem useful. I've added an initial implementation on a branch https://github.com/phronmophobic/clj-graphviz/tree/subgraphs.

The docs still need updating, but you can see an example [here](https://github.com/phronmophobic/clj-graphviz/blob/subgraphs/notebooks/docs.clj#L211).

**Comment by phronmophobic** [comment]
Ok, just pushed version 0.6.1. You can see example usage at https://phronmophobic.github.io/clj-graphviz/#subgraphs-and-clusters . Let me know if you have any questions, suggestions, or improvements!

**Comment by phronmophobic** [comment]
I think this issue has been addressed, but feel free to reopen if I missed something.

**Comment by x64-latacora** [comment]
Brilliant, thanks @phronmophobic :pray: . I'll use this feature and ping back with any feedback.
